#include "Driver/rf.h"
#include "hal.h"
#include "stm32c051xx.h"

void SYS_RF_InitPins(void) {
	// RF_IRQs
	HAL_GPIO_Init(GPIOA, 1, GPIO_MODE_INPUT, GPIO_PULL_DOWN);

	// RF_NRST
	HAL_GPIO_Init(GPIOA, 2, GPIO_MODE_OUTPUT, GPIO_PULL_UP);

	// RF_BUSY
	HAL_GPIO_Init(GPIOA, 3, GPIO_MODE_INPUT, GPIO_PULL_DOWN);

	// RF_NSS
	HAL_GPIO_Init(GPIOA, 4, GPIO_MODE_OUTPUT, GPIO_PULL_NONE);
	HAL_GPIO_WriteHigh(GPIOA, 4);

	// RF_SCK
	HAL_GPIO_Init(GPIOA, 5, GPIO_MODE_AF, GPIO_PULL_NONE);
	HAL_GPIO_AF_Init(GPIOA, 5, 0);

	// RF_MISO
	HAL_GPIO_Init(GPIOA, 6, GPIO_MODE_AF, GPIO_PULL_NONE);
	HAL_GPIO_AF_Init(GPIOA, 6, 0);

	// RF_MOSI
	HAL_GPIO_Init(GPIOA, 7, GPIO_MODE_AF, GPIO_PULL_NONE);
	HAL_GPIO_AF_Init(GPIOA, 7, 0);
}